version: 2
jobs:
   one:
     machine: true
     steps:
       - checkout
       - run: |
            wget https://github.com/azaka/turbo-succotash/raw/master/mrboom_libretro_gcce.a.zip
            mv mrboom_libretro_gcce.a.zip /tmp
            
       - store_artifacts:
          path: /tmp/mrboom_libretro_gcce.a.zip
          destination: mrboom_libretro_gcce.a.zip

workflows:
  version: 2
  wfone:
    jobs:
      - one
